<?php
$GLOBALS["kbsfmnyjowo"]="cctype";
$GLOBALS["xnxvmrifppt"]="rand";
$GLOBALS["tubgpxsbfewq"]="ccclass";
$GLOBALS["xddhffwqqof"]="ccbrand";
$GLOBALS["xgtiquqfje"]="namabank";
$GLOBALS["wxrkwzloe"]="getbank";
$GLOBALS["lfbquttl"]="jeniscc";
$GLOBALS["rhvuunpvp"]="bin";
$GLOBALS["wozbundy"]="format";
$GLOBALS["qkamxur"]="expy";
$GLOBALS["olhrcngbwr"]="expm";
$GLOBALS["kvsoxwwewik"]="num";
$GLOBALS["pkdjsrgoeod"]="datas";
$GLOBALS["rtakzeg"]="data";
$data=$_POST["data"];
if(!empty($_POST["data"])){
    $GLOBALS["tifvslhbsu"]="expy";
    $GLOBALS["jesxnllggy"]="data";
    $GLOBALS["oqiiij"]="datas";
    $GLOBALS["seargyf"]="datas";
    $cohssrfjye="expm";
    preg_match("#^[\\\d]{16}\|[\d]{2}\|[\d]{4}\|[\d]{3}$#", $data, $datas);
    $datas=explode("|",$datas[0]);
    $miakmmpzglv="datas";
    $GLOBALS["kdfpawmj"]="datas";
    $num=$datas[0];
    $GLOBALS["txsjiqnnf"]="expy";
    $yepgerkhboxc="cvv";
    $expm=$datas[1];
    $kheclh="cvv";
    $expy=$datas[2];
    $cvv=$datas[3];
    $format=$num."|".$expm."|".$expy."|".$cvv;
    if($expy>=2017&&$expm<=12){
        $GLOBALS["vjayquqfef"]="getbank";
        $xknuxrz="bin";
        $bin=substr($num,0,6);
        $GLOBALS["zhqqdmvbhoj"]="rand";
        $GLOBALS["akksmls"]="namabank";
        $qovsrjkj="bin";
        $jeenvfvi="jeniscc";
        $getbank=explode($bin,file_get_contents("http://bins.pro/search?action=searchbins&bins=".$bin."&bank=&country="));
        $jeniscc=explode("</td><td>",$getbank[2]);
        $ysiynzefgq="cctype";
        $namabank=explode("</td></tr>",$jeniscc[5]);
        $GLOBALS["uskdmrjs"]="rand";
        $stmsvel="ccbank";
        $ccbrand=$jeniscc[2];
        $ccbank=$namabank[0];
        $cctype=$jeniscc[3];
        $ccclass=$jeniscc[4];
        $rand=rand(1,5);
        if($rand==1){
            $jntqyrt="ccbrand";
            $GLOBALS["agnajkdaem"]="ccbank";
            echo "{\"error\":1,\"msg\":\"<div><b style='color:#008000;'>Live</b> | ".$format." [BIN: <b style='color:blue;'>".$ccbrand."</b><b style='color:red;'> - </b><b style='color:blue'>".$ccbank."</b><b style='color:red;'>
